# Generated by Django 5.2 on 2025-05-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('poster_url', models.URLField()),
            ],
        ),
    ]
