# Generated by Django 5.2 on 2025-05-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_country_topic_delete_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
