# Generated by Django 5.2 on 2025-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('api', '0002_category_country_topic_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.FloatField(default=0.0, max_length=5)),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies', verbose_name='Movie_Image')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Vietnamese', 'Vietnamese'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('French', 'French'), ('Spanish', 'Spanish'), ('German', 'German'), ('Italian', 'Italian'), ('Russian', 'Russian')], default='English', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ManyToManyField(blank=True, to='actor.actor')),
                ('category', models.ManyToManyField(blank=True, to='api.category')),
                ('country', models.ManyToManyField(blank=True, to='api.country')),
                ('topic', models.ManyToManyField(blank=True, to='api.topic')),
            ],
        ),
    ]
