# Generated by Django 5.2 on 2025-05-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='movies/avatar/', verbose_name='Movie_Image_Avatar'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_ads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
