# Generated by Django 5.2 on 2025-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_image_avatar_movie_is_ads_movie_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Videos'),
        ),
    ]
