# Generated by Django 5.2 on 2025-05-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_options_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/', verbose_name='Videos'),
        ),
    ]
