# Generated by Django 5.2 on 2025-06-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_topmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmovie',
            name='level',
            field=models.IntegerField(default=5),
        ),
    ]
