# Generated by Django 5.2 on 2025-05-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
